local hyper = require("hyper")

hyper.bindApp({}, "a", "Arc")
hyper.bindApp({}, "w", "Warp")
hyper.bindApp({}, "s", "Slack")
hyper.bindApp({}, "1", "1Password")
hyper.bindApp({}, "r", "Rize")
hyper.bindApp({}, "d", "Obsidian")
hyper.bindApp({}, "c", "Google Chrome")
hyper.bindApp({}, "t", "Notification Center")
